domain: https://discordbots.co.uk
baseurl: ""
url: https://discordbots.co.uk
encoding: utf-8

plugins:
  - jekyll-polyglot
  - jekyll-sitemap

include: 
  - _pages
  - _pages/api
  - _pages/api/bots
  - _pages/api/servers
  - _pages/oauth

exclude:
  - assets/css/ModestaCSS/_pages
  - webpack/
  - .sass-cache/
  - node_modules/
  - webpack.config.js
  - package.json
  - package-lock.json
  - Gemfile.lock

languages:
  - en
  - fr

default_lang: en
exclude_from_localization:
  - assets
parallel_localization: true

sass:
  sass_dir: _sass
  style: compressed

collections:
  docs:
    output: true
    permalink: /:collection/:name/
  bots:
    output: true
    permalink: /:collection/:name/
  servers:
    output: true
    permalink: /:collection/:name/
  bans:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: item
      type: docs
      layout: docs
      primary_key: slug
  - scope:
      path: ""
      type: bots
    values:
      layout: item
      type: bots
      lang: en
      primary_key: client_id
  - scope:
      path: ""
      type: servers
    values:
      layout: item
      type: servers
      primary_key: server_id
